name: Analyze
on: [push, pull_request]
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
        queries: +security-and-quality
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        virtualenv .venv
        source .venv/bin/activate
        pip3 install -r ./requirements.txt
    - run: source .venv/bin/activate && pytest
  flake8:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install flake8
      run: |
        sudo apt update
        sudo apt install -y flake8
    - name: Execute flake8 on the repository
      run: flake8
